// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerAnalysis.Data;

#nullable disable

namespace PowerAnalysis.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112102205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PowerAnalysis.Models.LoadReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataSource")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoadValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSource")
                        .HasDatabaseName("IX_LoadReading_DataSource");

                    b.HasIndex("Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_LoadReading_Timestamp");

                    b.HasIndex("Timestamp", "DataSource")
                        .HasDatabaseName("IX_LoadReading_Timestamp_DataSource");

                    b.ToTable("LoadReadings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
